namn = input("Vad heter du?")
print(namn, "är ett fint namn.")
mat = input("Vilken mat gillar du?")
print(namn, mat, "är verkligen gott.")
pengar = input("Hur mycket pengar har du i fickan?")
print(namn, "oj, det var inte mycket.")